FROM public.ecr.aws/sam/build-python3.12:latest-x86_64

WORKDIR /var/task

# Copy only requirements first to leverage Docker cache
COPY ../../../src/requirements.txt .

# Install dependencies specifically for Linux Lambda
RUN pip install -r requirements.txt --target ./dist

# Copy the actual handler code
COPY ../../../src/handler.py ./dist/

# Set permissions
RUN chmod -R 755 .