FROM public.ecr.aws/lambda/python:3.12

# Context is now the VinciFlow/ folder
COPY backend/src/requirements.txt .
RUN pip install -r requirements.txt

COPY backend/src/handler.py .

CMD [ "handler.handler" ]